### ISSUE TITLE
Gauge 'red' seems to be missing

### ISSUE THREAD

**Issue by Nornode** [aFFekopp/noctis#16]
```
type: gauge
    entity: sensor.temp
    max: 30
    min: 20
    name: temperature
    severity:
      green: 22
      yellow: 24
      red: 26
```
I'm using this amazing theme however using it, I fail to get red colours on my gauges.
If you still maintain it, please add it. :)
