### ISSUE TITLE
Wrong colors with vertical-stack-in-card

### ISSUE THREAD

**Issue by bieniu** [aFFekopp/noctis#2]
I use `vertical-stack-in-card` to join `glance` and `entities` cards. Your theme colors are wrong with that configuration.
```yaml
         - type: custom:vertical-stack-in-card
            title: "Sypialnia"
            cards:
              - type: glance
                show_name: false
                entities:
                  - sensor.temperature_sypialnia
                  - sensor.humidity_sypialnia
                  - sensor.illumination_sypialnia
              - type: entities
                style: |
                  .card-content {
                    padding-top: 0px;
                  }
                show_header_toggle: false
                entities:
                  - binary_sensor.window_sypialnia
                  - binary_sensor.balcony_door_sypialnia
                  - entity: binary_sensor.motion_sypialnia
                    secondary_info: last-changed
                  - climate.thermostat_sypialnia
                  - light.lightstrip_sypialnia
                  - switch.christmas_lights_sypialnia
```
![obraz](https://user-images.githubusercontent.com/478555/72613802-ec116d80-3930-11ea-9139-5a5906c0f3ab.png)
