### ISSUE TITLE
Layout colors are off since version 2022.3.0

### ISSUE THREAD

**Issue by smarthomejunkie** [aFFekopp/noctis#25]
In some areas in Home Assistant the layout colors are not correct anymore. See for instance the developer tools.
![Screenshot_31](https://user-images.githubusercontent.com/67226335/156561250-8020512d-7c0c-4c24-94d9-19a05d9b3bd0.png)
.

**Comment by smarthomejunkie** [comment]
Brilliant! Thx! 🙏🏻

**Comment by krazos** [comment]
Many thanks for the quick fix!  I've noticed one lingering issue after the latest update.

The unit of measurement shown in the `input_number` selector box should be `var(--text-color)` (or at least some color other than black) to improve contrast against the dark background.  I struggled to find the right style tag for the unit of measurement when I was trying to quickly patch a couple of my broken themes during the beta, so I will defer to the experts. 

Screenshot:

![Screenshot from 2022-03-04 07-45-39](https://user-images.githubusercontent.com/18428022/156766258-5ce7502d-5186-4f4d-b971-f53c737e7d73.png)

Lovelace YAML:

```yaml
type: entities
entities:
  - entity: input_number.great_room_pellet_stove_setpoint_home
    name: Home
  - entity: input_number.great_room_pellet_stove_setpoint_morning
    name: Morning
  - entity: input_number.great_room_pellet_stove_setpoint_night
    name: Night
  - entity: input_number.great_room_pellet_stove_setpoint_away
    name: Away
title: Setpoints
```
