### ISSUE TITLE
Light card dimmer control invisible

### ISSUE THREAD

**Issue by metbril** [aFFekopp/noctis#6]
The dimmer control in the light card is invisible.

```
title: Verlichting
path: lighthing
icon: 'mdi:lightbulb'

cards:

  - type: horizontal-stack
    cards:

      - type: light
        entity: light.living_dusk
        name: Schemer

      - type: light
        entity: light.leeslamp

      - type: light
        entity: light.living
```
![3CD1D61B-8D0B-4442-9D9D-19F727C164F6](https://user-images.githubusercontent.com/559346/72866793-ed4dec00-3cdc-11ea-8d5f-671f95bae2d6.jpeg)
![B1ED6FD5-CE4F-4965-8601-52498490B853](https://user-images.githubusercontent.com/559346/72866795-ed4dec00-3cdc-11ea-9ce7-0abbcb16293b.jpeg)
