### ISSUE TITLE
Lost colors in gauge

### ISSUE THREAD

**Issue by oalbaf** [aFFekopp/noctis#9]
v1.7 lost colors of gauge:

![Screenshot_20200122-215613_Chrome](https://user-images.githubusercontent.com/31956250/72933575-46139800-3d62-11ea-8f03-dc366cf492d1.jpg)

If I select other them in download gauge:
![20200122_215132](https://user-images.githubusercontent.com/31956250/72933644-6d6a6500-3d62-11ea-92cb-de458d3f5321.jpg)

In 1.6 version work well

**Comment by aFFekopp** [comment]
I can't  seem to recreate this. What do you mean with if you select other?

Can you post a code example?

**Comment by oalbaf** [comment]
Hi!

Put this code in manual card in Lovelance (change my sensor.speedtest_ping for a input_number for example)

```
entity: sensor.speedtest_ping
max: 100
min: 0
name: Ping
severity:
  green: 0
  red: 100
  yellow: 10
theme: Backend-selected
type: gauge

```

Thanks for your work! It's a nice theme!

**Comment by aFFekopp** [comment]
I think `theme: Backend-selected` is the problem, try removing that. This should fix it.

**Comment by oalbaf** [comment]
My backend-selected is noctis. And I now remove that but the problem don't fix.

**Comment by aFFekopp** [comment]
And if you set it to `theme: noctis`? I'm wondering why only the middle one is white

**Comment by oalbaf** [comment]
Same problem if I `theme: noctis`

In version 1.6 work well

![image](https://user-images.githubusercontent.com/31956250/72936668-f3d57580-3d67-11ea-97c0-84be6ee44112.png)

**Comment by aFFekopp** [comment]
Now i see that you mean the severity color. The Problem is many theme variables are used in multiple places. 

I changed the label-badge colors to change the color of the badges. The same colors are also used for the gauge-card.

What you can do is create another theme. Create a file called `gauge_colors.yaml` in your `themes` folder with the following content

```
gauge_colors:
  label-badge-red: 'rgba(247,53,67,1)'
  label-badge-blue: 'rgba(26,137,245,1)'
  label-badge-green: 'rgba(0,202,139,1)'
  label-badge-yellow: 'rgba(222,176,107,1)'
```
and then set in your gauge cards
`theme: gauge_colors`

If I change those colors in the theme, then you would get red badges.
